{{- with required ".sessions.limitRangeSpec is required." .Values.sessions.limitRangeSpec }}
---
apiVersion: v1
kind: LimitRange
metadata:
    name: {{ $.Release.Name }}-session-limit-range
    namespace: {{ $.Values.sessions.namespace }}
spec:
  limits:
    - type: Container
{{- if .max }}
      max:
{{ toYaml .max | indent 8 }}
{{- end }}
{{- if .default }}
      default:
{{ toYaml .default | indent 8 }}
{{- end }}
{{- if .defaultRequest }}
      defaultRequest:
{{ toYaml .defaultRequest | indent 8 }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-session-limit-range-role
  namespace: {{ .Values.sessions.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - limitranges
  verbs:
  - get
  - list
  - status
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-session-limit-range
  namespace: {{ .Values.sessions.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-session-limit-range-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName | required ".Values.serviceAccountName value is required" }}
  namespace: {{ .Release.Namespace }}
